### ISSUE TITLE
Confusion on how to implement.  Not finding the login view.

### ISSUE THREAD

**Issue by BrianWaganerSTL** [AzMoo/django-okta-auth#19]
I know this is simple but I'm not following where I should put my okta_oauth2/login.html template.  Do I need to create an okta_oauth2 application, I would not think so since it's already included.  I also would not think it would be in the directory installed with pip.  Just not quite following.

```
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: Internal Server Error: /api/auth/okta/login/
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: Traceback (most recent call last):
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: File "/opt/dbaas/RocketDBaaS_api/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: response = get_response(request)
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: File "/opt/dbaas/RocketDBaaS_api/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: File "/opt/dbaas/RocketDBaaS_api/venv/lib/python3.6/site-packages/okta_oauth2/views.py", line 30, in login
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: response = render(request, "okta_oauth2/login.html", {"config": okta_config})
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: File "/opt/dbaas/RocketDBaaS_api/venv/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: content = loader.render_to_string(template_name, context, request, using=using)
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: File "/opt/dbaas/RocketDBaaS_api/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: template = get_template(template_name, using=using)
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: File "/opt/dbaas/RocketDBaaS_api/venv/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: raise TemplateDoesNotExist(template_name, chain=chain)
Oct 12 18:21:22 ch3dr1012100 gunicorn[9176]: django.template.exceptions.TemplateDoesNotExist: okta_oauth2/login.html
```

Also another question of mine is regarding the AUTHENTICATION_BACKENDS.  Can I have others or just the OktaBackend.
```
AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
    'okta_oauth2.backend.OktaBackend',
]
```

**Comment by AzMoo** [comment]
This was forever ago and I assume now irrelevant. Sorry I didn't reply, I wasn't monitoring the repo.
