### ISSUE TITLE
Doesn't work in Django 4.x?

### ISSUE THREAD

**Issue by mekhami** [AzMoo/django-okta-auth#32]
backend_1   | Traceback (most recent call last):
backend_1   |   File "/code/manage.py", line 22, in <module>
backend_1   |     main()
backend_1   |   File "/code/manage.py", line 18, in main
backend_1   |     execute_from_command_line(sys.argv)
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
backend_1   |     utility.execute()
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
backend_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
backend_1   |     self.execute(*args, **cmd_options)
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
backend_1   |     output = self.handle(*args, **options)
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
backend_1   |     res = handle_func(*args, **kwargs)
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 97, in handle
backend_1   |     self.check(databases=[database])
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
backend_1   |     all_issues = checks.run_checks(
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
backend_1   |     new_errors = check(app_configs=app_configs, databases=databases)
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
backend_1   |     return check_resolver(resolver)
backend_1   |   File "/py/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
backend_1   |     return check_method()
backend_1   |   File "/py/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
backend_1   |     for pattern in self.url_patterns:
backend_1   |   File "/py/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
backend_1   |     res = instance.__dict__[self.name] = self.func(instance)
backend_1   |   File "/py/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
backend_1   |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
backend_1   |   File "/py/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
backend_1   |     res = instance.__dict__[self.name] = self.func(instance)
backend_1   |   File "/py/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
backend_1   |     return import_module(self.urlconf_name)
backend_1   |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
backend_1   |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
backend_1   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
backend_1   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
backend_1   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
backend_1   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
backend_1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend_1   |   File "/code/index_data_platform/urls.py", line 25, in <module>
backend_1   |     "accounts/", include("okta_oauth2.urls", "okta_oauth2"), namespace="okta_oauth2"
backend_1   |   File "/py/lib/python3.10/site-packages/django/urls/conf.py", line 42, in include
backend_1   |     raise ImproperlyConfigured(
backend_1   | django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.

The urlconf doesn't work the way the readme provides it, and removing the namespaces breaks the middleware.

Can we get this updated to a recent version of Django?

**Comment by mekhami** [comment]
nevermind.
